### ISSUE TITLE
islandora-idc.traefik.me does not resolve to the right place

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idcApp-k8s#34]
Messages emitted by drupal to microservices contain URLs for the microservices to `PUT` derivatives once they're done prcessing.  These URLs have host `islandora-idc.traefik.me` in the development environment, and `MUST` identical Drupal's configured public URI hostname.  

A snippet of the message sent by Drupal is as follows:
<pre>
"target": null,
	"type": "Activity",
	"summary": "Generate Derivative",
	"attachment": {
		"type": "Object",
		"content": {
			"mimetype": "image/jpeg",
			"args": "",
			"source_uri": "http://<b>islandora-idc.traefik.me</b>/sites/default/files/2021-04/img_20200319_072100_dro.jpg",
			"destination_uri": "http://<b>islandora-idc.traefik.me</b>/node/33/media/image/19",
			"file_upload_uri": "public://2021-04/33-Service File.jpg"
		},
		"mediaType": "application/json"
	}
</pre>

The microservice (in this case, houdini) attempts to `GET` the `source_URI`, which fails because `islandora-idc.traefik.me` resolves to `127.0.0.1`.  It should resolve to whatever `drupal-service` resolves to, but needs to be `islandora-idc.traefik.me` (or whatever the public DNS name of Drupal is configured to be), and can't be `drupal-service`.

This affects the local development instance  of the k8s stack for sure, and may or may not affect cloud instances with proper DNS entries for Drupal.  

In the `docker-compose`-based development environment, this issue is fixed by declaring an `islandora-idc.traefik.me` `alias` for the Drupal container, which adds a DNS entry for `islandora-idc.traefik.me` pointing to the Drupal container for all backend services.

**Comment by birkland** [comment]
FYI, I tried merely creating a configmap for coredns (yaml file), but it doesn't seem that the updated configmap is actually mounted/read by the `coredns` containers.  At this point, I'll stop and move on to other things.

i.e. I created coredns_config.yaml containing the following:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
    errors
    health {
       lameduck 5s
    }
    ready
    rewrite name islandora-idc.traefik.me drupal-service
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    prometheus :9153
    forward . /etc/resolv.conf {
       max_concurrent 1000
    }
    cache 30
    loop
    reload
    loadbalance
    }
``` 
I added that to kustomize.yaml, and saw a message fly by when doing `kubectl apply`:
```configmap/coredns created```

However, it looks like the configmap mounted by the coredns containers is _not_ the one from _my_ configmap.  It's still the stock configmap that comes out of the box from docker desktop.  So, clearly I'm doing something wrong if I want coredns to use my configmap instead.

**Comment by derekbelrose** [comment]
Ok, I got this working locally. It's not intuitive as how it works this way and not the others that I tried.
According to my /etc/resolv.conf file in the pod it shows:
```
/ # cat /etc/resolv.conf 
search linuxdevelopment.svc.cluster.local svc.cluster.local cluster.local home.derekbelrose.com
nameserver 10.96.0.10
options ndots:5
```

As I have a service/mariadb-service, you'd expect the service to be available as `mariadb-service`, that's just not true:
```/ # dig +short mariadb-service
/ # dig +short mariadb-service.linuxdevelopment
/ # dig +short mariadb-service.linuxdevelopment.svc
/ # dig +short mariadb-service.linuxdevelopment.svc.cluster
/ # dig +short mariadb-service.linuxdevelopment.svc.cluster.local
10.96.236.4
```
The same works with Drupal, but I chose to use Mariadb as my rewrite target.

So we'll need to create a resource in the development/resources with the file and then a patch in each of the dev environments (linux, macos, wsl2) with a patch for the rewrite line. This might be more difficult that it's worth as patches may not work on the Corefile data, instead we might as well patch the whole Corefile data or just the whole system. Either way, it needs to be written to kube-system, so we might need to get clever here.

Either way, here's the working solution for me, haven't tested it on Windows yet, but as it's running coreDNS, it should be the same solution.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
    errors
    health {
       lameduck 5s
    }
    ready
    rewrite name exact islandora-idc.traefik.me drupal-service.linuxdevelopment.svc.cluster.local

    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    prometheus :9153
    forward . /etc/resolv.conf {
       max_concurrent 1000
    }
    cache 30
    loop
    reload
    loadbalance
    }
```

**Comment by derekbelrose** [comment]
@birkland I think I have this figured out. Please refresh your copy of idcApp-k8s.  The deployment method has changed slightly, the path has changed where you run kustomize build | kubectl.  Please use idcApp-k8s/overlays/development/deployment/wsl2

We needed to complicate things a little because of this need to rewrite DNS queries.  Once you get this running using the new path, you should be able to resolve islandora-idc.traefik.me in the cluster as 'drupal-service'.  Externally, it will still be 127.0.0.1.

**Comment by derekbelrose** [comment]
I believe this is no longer needed as we have moved away from this model but it does work locally if needed.
