### ISSUE TITLE
Cantaloupe should be a public service

### ISSUE THREAD

**Issue by jhujasonw** [jhu-idc/idcApp-k8s#43]
Cantaloupe should be a public service accessible via https://{fqdn}/cantaloupe/ and everything else at https://{fqdn}/ should forward to the drupal container.

I need to discuss this with @derekbelrose before we choose a method to make this happen.

**Comment by jhujasonw** [comment]
Currently blocks:

- https://github.com/jhu-idc/idcApp-k8s/issues/40
- https://github.com/jhu-idc/idcApp-k8s/issues/41
- https://github.com/jhu-idc/idc-isle-dc/issues/116
- https://github.com/jhu-idc/iDC-general/issues/248
- https://github.com/jhu-idc/iDC-general/issues/247
- https://github.com/jhu-idc/iDC-general/issues/249
-

**Comment by derekbelrose** [comment]
Does cantaloupe need to be behind SAML authentication?

**Comment by jhujasonw** [comment]
Aaron says no, that would interfere with anonymous access to view public images with an IIIF Viewer

**Comment by htpvu** [comment]
@jhujasonw can we close this ticket given the merging of  this https://github.com/jhu-idc/idcApp-k8s/pull/44

**Comment by derekbelrose** [comment]
I would say no because this is for al environments and the PR was just for test.

**Comment by jhujasonw** [comment]
https://github.com/jhu-idc/idcApp-k8s/issues/49 - for stage.

**Comment by jhujasonw** [comment]
Finished in all cloud instances.
Needs to be propagated to local dev.

**Comment by jhujasonw** [comment]
Finished in local instance, closing ticket.
