### ISSUE TITLE
Enable S3 in test instance

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idcApp-k8s#45]
S3 is required for all drupal-static images post ghcr.io/jhu-sheridan-libraries/idc-isle-dc/drupal-static:a5decfb 

* Create an S3 bucket for content, and setting appropriate permissions on it
* Deploy `drupal-static` version `a5decfb` or newer.
* [Configure Drupal](https://github.com/jhu-idc/idc-isle-dc#s3-file-storage) for the credentials and identity of the bucket
* Manually verify (or get somebody to verify) that Drupal can successfully store content in its configured S3 environment

Part of jhu-idc/iDC-general#342

**Comment by jhujasonw** [comment]
Need the TF Code for this, opened ticket for infrastructure code https://github.com/jhu-idc/idc-kubernetes/issues/25
