### ISSUE TITLE
Enable S3 in stage instance

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idcApp-k8s#46]
* Create an S3 bucket for content, and setting appropriate permissions on it
* Deploy `drupal-static` version `a5decfb` or newer.
* [Configure Drupal](https://github.com/jhu-idc/idc-isle-dc#s3-file-storage) for the credentials and identity of the bucket
* _if stage is deployed already_, manually verify (or get somebody to verify) that Drupal can successfully store content in its configured S3 environment.  If not, this will obviously not happen, and the ticket can be closed after all configuration is done.

Part of jhu-idc/iDC-general#342

**Comment by jhujasonw** [comment]
Changed merged, all four instances running on S3 backed storage.
